import openpyxl

file_paths = [
    r'd:\oil adulteration new\smart_food_dish_management_data.xlsx',
    r'd:\oil adulteration new\Smart_Food_Management_Dish_Database-1.xlsx',
    r'd:\oil adulteration new\backend\smart_food_dish_management_data.xlsx'
]

more_dishes = [
    # GUJARATI (15 Dishes)
    ('D2001', 'Steamed Methi Muthia', 'Gujarati', 'Breakfast/Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Medium', 15, 20, 3, 'Besan, Methi Leaves, Wheat Flour, Sesame Seeds, Turmeric', 190, 8, 30, 3.5, 5, 2, 240, 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2002', 'Oats Veggie Handvo', 'Gujarati', 'Breakfast/Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 25, 4, 'Oats, Bottle Gourd, Carrot, Besan, Curd, Mustard Seeds', 210, 9, 32, 4.0, 6, 2, 260, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2003', 'Sprouted Moong Khatta Dhokla', 'Gujarati', 'Breakfast/Snack', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 15, 20, 3, 'Sprouted Moong, Curd, Ginger Green Chili, Mustard Seeds', 170, 11, 26, 2.5, 5, 1, 230, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2004', 'Sev Khamani (Low Oil Chana Dal)', 'Gujarati', 'Breakfast/Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 20, 3, 'Chana Dal, Mustard Seeds, Pomegranate, Ginger, Lemon Juice', 220, 10, 34, 4.5, 6, 3, 270, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2005', 'Baked Bajra Oats Fafda', 'Gujarati', 'Breakfast/Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 15, 3, 'Bajra Flour, Oats Flour, Besan, Ajwain, Olive Oil', 160, 6, 26, 3.5, 4, 1, 210, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2006', 'Masala Gujarati Poha', 'Gujarati', 'Breakfast', 'Grain', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 10, 2, 'Poha, Potato, Peanuts, Mustard Seeds, Turmeric, Lemon Juice', 215, 6, 38, 5.0, 4, 3, 230, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2007', 'Dudhi Chana Dal Shaak', 'Gujarati', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 20, 3, 'Bottle Gourd (Dudhi), Chana Dal, Tomato, Cumin, Mustard Seeds', 200, 10, 32, 3.0, 7, 3, 250, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2008', 'Bhinda Nu Shaak (Low Oil Okra)', 'Gujarati', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 15, 2, 'Bhindi (Okra), Ajwain, Turmeric, Coriander Powder, Olive Oil', 140, 4, 18, 5.5, 6, 2, 210, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2009', 'Ringan No Oro (Gujarati Baingan Bharta)', 'Gujarati', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 20, 2, 'Roasted Eggplant, Garlic, Tomato, Spring Onion, Mustard Oil', 180, 5, 22, 7.0, 8, 4, 240, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2010', 'Gujarati Kadhi (Sugar-Free)', 'Gujarati', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'No', 'Mild', 'Easy', 10, 15, 3, 'Low-Fat Curd, Besan, Ginger, Green Chili, Curry Leaves, Mustard Seeds', 130, 6, 14, 4.5, 2, 2, 280, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2011', 'Steamed Patra (Colocasia Roll)', 'Gujarati', 'Snack', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 25, 3, 'Arbi Leaves, Besan, Tamarind Pulp, Sesame Seeds, Spices', 175, 7, 28, 3.0, 5, 2, 230, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2012', 'Bajra Rotla with Lasaniya Marchu', 'Gujarati', 'Dinner', 'Bread', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 15, 2, 'Bajra Flour, Garlic, Red Chili, Sesame Seeds, Olive Oil', 240, 7, 44, 4.0, 7, 1, 260, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2013', 'Vaghareli Brown Rice Khichdi', 'Gujarati', 'Dinner', 'Khichdi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 20, 3, 'Brown Rice, Yellow Moong Dal, Cumin, Mustard Seeds, Turmeric', 260, 11, 46, 3.5, 6, 2, 270, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2014', 'Sprouted White Vatana Shaak', 'Gujarati', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 25, 3, 'Sprouted White Peas, Tomato, Ginger, Garam Masala', 220, 12, 36, 2.5, 8, 3, 290, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2015', 'Oats & Date Sugar-Free Sukhdi', 'Gujarati', 'Snack/Dessert', 'Dessert', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 10, 4, 'Oats Flour, Seedless Dates, Cardamom, Ghee', 150, 4, 24, 4.5, 3, 8, 80, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),

    # SOUTH INDIAN (15 Dishes)
    ('D2016', 'Oats Rava Vegetable Idli', 'South Indian', 'Breakfast', 'Steamed', 'Vegetarian', 'No', 'Mild', 'Easy', 15, 15, 3, 'Rolled Oats, Rava, Curd, Carrots, Peas, Mustard Seeds', 180, 8, 32, 2.5, 5, 2, 230, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2017', 'Pesarattu (Sprouted Moong Dosa)', 'South Indian', 'Breakfast', 'Bread', 'Vegetarian', 'Yes', 'Mild', 'Medium', 15, 15, 2, 'Sprouted Green Moong, Ginger, Green Chili, Cumin', 210, 13, 33, 3.0, 7, 1, 240, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2018', 'Ragi Vegetable Uthappam', 'South Indian', 'Breakfast', 'Bread', 'Vegetarian', 'Yes', 'Mild', 'Medium', 15, 15, 2, 'Ragi Flour, Onion, Tomato, Capsicum, Green Chili', 200, 7, 38, 2.5, 6, 2, 250, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2019', 'Foxtail Millet Ven Pongal', 'South Indian', 'Breakfast/Lunch', 'Grain', 'Vegetarian', 'No', 'Mild', 'Easy', 15, 20, 3, 'Foxtail Millet, Moong Dal, Black Pepper, Cumin, Ghee, Cashews', 250, 10, 42, 5.0, 6, 1, 260, 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2020', 'Red Rice Vegetable Puttu', 'South Indian', 'Breakfast', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 15, 20, 3, 'Red Rice Flour, Grated Coconut, Water, Cardamom', 190, 5, 38, 2.0, 4, 2, 190, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2021', 'Kerala Vegetable Avial (Low Coconut)', 'South Indian', 'Lunch', 'Curry', 'Vegetarian', 'No', 'Mild', 'Medium', 20, 20, 3, 'Carrots, Drumstick, Pumpkin, Beans, Low-Fat Curd, Coconut', 210, 6, 24, 9.0, 7, 4, 270, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2022', 'Beetroot Poriyal (Low Oil)', 'South Indian', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 15, 2, 'Beetroot, Mustard Seeds, Curry Leaves, Grated Coconut, Oil', 130, 3, 20, 3.5, 5, 5, 200, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2023', 'Drumstick Sambar with Brown Rice', 'South Indian', 'Lunch', 'Rice', 'Vegetarian', 'Yes', 'Medium', 'Medium', 20, 30, 3, 'Toor Dal, Drumstick, Brown Rice, Sambar Masala, Tamarind', 320, 13, 56, 3.5, 9, 3, 340, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2024', 'Brown Rice Lemon Curd Rice', 'South Indian', 'Lunch/Dinner', 'Rice', 'Vegetarian', 'No', 'Mild', 'Easy', 15, 15, 2, 'Brown Rice, Low-Fat Curd, Lemon Juice, Mustard Seeds, Curry Leaves', 260, 9, 44, 4.5, 4, 2, 280, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2025', 'Tomato Pepper Rasam', 'South Indian', 'Dinner', 'Soup', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 15, 2, 'Tomatoes, Black Pepper, Cumin, Garlic, Tamarind, Mustard Seeds', 85, 2, 16, 1.0, 3, 3, 210, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2026', 'Cabbage Thoran (Kerala Style)', 'South Indian', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 15, 2, 'Cabbage, Turmeric, Mustard Seeds, Coconut, Curry Leaves', 125, 4, 16, 4.0, 5, 3, 220, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2027', 'Mushroom Pepper Fry (South Style)', 'South Indian', 'Dinner/Snack', 'Stir-Fry', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 12, 2, 'Button Mushrooms, Black Pepper, Onion, Curry Leaves, Fennel', 150, 7, 14, 6.0, 4, 2, 250, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2028', 'Sprouted Black Chana Sundal', 'South Indian', 'Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 10, 2, 'Sprouted Black Chana, Mustard Seeds, Curry Leaves, Coconut', 175, 11, 27, 2.5, 7, 1, 220, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2029', 'Baked Chana Dal Masala Vada', 'South Indian', 'Snack', 'Snack', 'Vegetarian', 'Yes', 'Medium', 'Medium', 20, 20, 3, 'Chana Dal, Fennel Seeds, Onion, Green Chili, Curry Leaves', 190, 9, 29, 3.5, 6, 2, 260, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2030', 'Kozhukattai (Steamed Veg Modak)', 'South Indian', 'Snack', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 20, 3, 'Rice Flour, Grated Carrots, Beans, Spices, Coconut', 160, 4, 32, 2.0, 4, 2, 190, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),

    # PUNJABI (15 Dishes)
    ('D2031', 'Whole Wheat Stuffed Gobi Paratha', 'Punjabi', 'Breakfast', 'Bread', 'Vegetarian', 'Yes', 'Medium', 'Medium', 25, 15, 2, 'Whole Wheat Atta, Cauliflower, Green Chili, Carom Seeds', 260, 8, 46, 4.5, 6, 2, 300, 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2032', 'Paneer Methi Whole Wheat Paratha', 'Punjabi', 'Breakfast', 'Bread', 'Vegetarian', 'No', 'Medium', 'Medium', 20, 15, 2, 'Paneer, Fresh Methi, Whole Wheat Atta, Spices', 290, 15, 40, 8.0, 5, 2, 330, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2033', 'Whole Wheat Tandoori Kulcha', 'Punjabi', 'Breakfast/Lunch', 'Bread', 'Vegetarian', 'No', 'Mild', 'Medium', 25, 15, 2, 'Whole Wheat Atta, Boiled Potato, Paneer, Curd, Carom Seeds', 280, 11, 48, 5.0, 5, 3, 310, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2034', 'Punjabi Spinach Egg Bhurji', 'Punjabi', 'Breakfast/Lunch', 'Scramble', 'Egg-itarian', 'No', 'Medium', 'Easy', 10, 10, 2, 'Eggs, Fresh Spinach, Onion, Tomato, Green Chili, Cumin', 210, 16, 8, 12.0, 3, 2, 340, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2035', 'Sarson Ka Saag with Missi Roti', 'Punjabi', 'Lunch', 'Curry', 'Vegetarian', 'Yes', 'Medium', 'Medium', 20, 35, 3, 'Mustard Greens, Spinach, Besan, Cornmeal, Ginger, Garlic', 310, 12, 48, 6.0, 9, 3, 350, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2036', 'Dal Makhani (Healthy Tofu Version)', 'Punjabi', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Mild', 'Medium', 25, 40, 4, 'Black Urad Dal, Rajma, Tofu, Tomato Puree, Garam Masala', 270, 15, 38, 5.5, 8, 2, 330, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2037', 'Punjabi Bhindi Masala (Low Oil)', 'Punjabi', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 20, 3, 'Bhindi (Okra), Onion, Tomato, Amchur Powder, Cumin', 160, 5, 22, 5.0, 7, 3, 260, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2038', 'Punjabi Baingan Bharta', 'Punjabi', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Medium', 20, 25, 3, 'Roasted Eggplant, Tomato, Onion, Garlic, Green Chili', 190, 6, 24, 7.0, 9, 4, 270, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2039', 'Baked Besan Kadhi Pakora', 'Punjabi', 'Lunch', 'Curry', 'Vegetarian', 'No', 'Medium', 'Medium', 20, 30, 3, 'Low-Fat Curd, Besan, Baked Spinach Pakora, Methi Seeds', 250, 11, 32, 7.5, 4, 3, 360, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2040', 'Aloo Baingan Punjabi Masala', 'Punjabi', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 20, 3, 'Potato, Eggplant, Tomato, Garlic, Coriander Powder', 210, 5, 36, 4.5, 6, 3, 280, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2041', 'Tandoori Paneer Tikka Skewers', 'Punjabi', 'Dinner/Snack', 'Grill', 'Vegetarian', 'No', 'Medium', 'Medium', 20, 15, 2, 'Paneer, Capsicum, Onion, Curd, Ajwain, Garam Masala', 270, 18, 12, 16.0, 3, 3, 340, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2042', 'Tandoori Soya Chunks Tikka', 'Punjabi', 'Dinner/Snack', 'Grill', 'Vegetarian', 'No', 'Medium', 'Medium', 20, 15, 2, 'Soya Chunks, Curd, Chaat Masala, Kasuri Methi, Lemon', 240, 24, 18, 6.0, 7, 2, 330, 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2043', 'Punjabi Spicy Chana Chaat', 'Punjabi', 'Snack', 'Snack', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 10, 2, 'Boiled Chickpeas, Cucumber, Onion, Lemon Juice, Chaat Masala', 190, 10, 32, 2.5, 7, 2, 280, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2044', 'Mushroom Matar Punjabi Masala', 'Punjabi', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 20, 3, 'Button Mushrooms, Green Peas, Tomato, Ginger Garlic, Spices', 195, 9, 26, 5.0, 6, 4, 300, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2045', 'Palak Paneer Punjabi Curry', 'Punjabi', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'No', 'Medium', 'Medium', 20, 20, 3, 'Fresh Spinach, Paneer, Garlic, Onion, Tomato, Cumin', 260, 16, 14, 15.0, 5, 2, 330, 'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),

    # MAHARASHTRIAN (15 Dishes)
    ('D2046', 'Sprouted Kanda Poha', 'Maharashtrian', 'Breakfast', 'Grain', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 12, 2, 'Poha, Sprouted Moong, Onion, Mustard Seeds, Turmeric, Peanuts', 220, 8, 36, 4.5, 5, 3, 240, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2047', 'Multigrain Thalipeeth', 'Maharashtrian', 'Breakfast', 'Bread', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 15, 2, 'Jowar, Bajra, Besan, Wheat Flour, Onion, Coriander, Ajwain', 240, 9, 42, 4.0, 6, 2, 260, 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2048', 'Oats Sabudana Khichdi', 'Maharashtrian', 'Breakfast/Snack', 'Grain', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 15, 2, 'Rolled Oats, Sabudana, Roasted Peanuts, Green Chili, Cumin', 230, 7, 38, 5.5, 4, 1, 220, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2049', 'Dadpe Pohe with Fresh Coconut', 'Maharashtrian', 'Breakfast/Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 0, 2, 'Thin Poha, Fresh Coconut, Lemon Juice, Mustard Seeds, Green Chili', 180, 4, 30, 4.5, 3, 2, 210, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2050', 'Veggie Rava Upma', 'Maharashtrian', 'Breakfast', 'Grain', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 12, 2, 'Rava, Carrots, Peas, Mustard Seeds, Curry Leaves, Cashews', 210, 6, 38, 3.5, 4, 2, 250, 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2051', 'Pithla with Jowar Bhakri', 'Maharashtrian', 'Lunch', 'Curry', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 20, 2, 'Besan, Garlic, Green Chili, Turmeric, Jowar Flour', 280, 12, 48, 4.0, 7, 2, 310, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2052', 'Bharli Vangi (Stuffed Baingan)', 'Maharashtrian', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Medium', 20, 25, 3, 'Small Eggplants, Roasted Peanuts, Sesame Seeds, Goda Masala', 220, 6, 22, 11.0, 7, 4, 290, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2053', 'Sprouted Matki Usal', 'Maharashtrian', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Spicy', 'Easy', 15, 20, 3, 'Sprouted Moth Beans, Onion, Tomato, Mustard Seeds, Curry Leaves', 210, 13, 34, 3.0, 8, 3, 300, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2054', 'Vegetable Kolhapuri (Low Oil)', 'Maharashtrian', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Spicy', 'Medium', 20, 25, 3, 'Mix Vegetables, Poppy Seeds, Coconut, Whole Spices, Garlic', 230, 7, 28, 9.0, 8, 4, 330, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2055', 'Varan Bhaat (Brown Rice)', 'Maharashtrian', 'Lunch', 'Rice', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 20, 2, 'Toor Dal, Brown Rice, Turmeric, Cumin, Hing', 270, 11, 50, 2.5, 6, 1, 260, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2056', 'Zunka with Bajra Bhakri', 'Maharashtrian', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Medium', 'Easy', 15, 15, 2, 'Besan, Onion, Garlic, Mustard Seeds, Bajra Flour', 290, 11, 46, 5.0, 8, 2, 320, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2057', 'Steamed Kothimbir Vadi', 'Maharashtrian', 'Snack', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 20, 3, 'Coriander Leaves, Besan, Sesame Seeds, Turmeric, Chili Powder', 170, 8, 26, 3.5, 5, 2, 240, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2058', 'Steamed Aluvadi (Colocasia)', 'Maharashtrian', 'Snack', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 20, 3, 'Colocasia Leaves, Besan, Tamarind, Sesame Seeds, Jaggery-free', 165, 7, 25, 3.0, 5, 2, 230, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2059', 'Sol Kadhi with Grilled Fish', 'Maharashtrian', 'Dinner', 'Grill', 'Non-Vegetarian', 'No', 'Medium', 'Easy', 15, 15, 2, 'Kokum Extract, Coconut Milk, Garlic, Fish Fillet, Olive Oil', 250, 26, 8, 12.0, 2, 1, 350, 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2060', 'Shengdana Chutney with Bhakri', 'Maharashtrian', 'Dinner/Snack', 'Bread', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 10, 2, 'Roasted Peanuts, Garlic, Red Chili, Jowar Bhakri', 260, 9, 38, 8.0, 5, 1, 250, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),

    # BENGALI (15 Dishes)
    ('D2061', 'Chirer Poha (Bengali Flattened Rice)', 'Bengali', 'Breakfast', 'Grain', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 10, 2, 'Flattened Rice (Chira), Peas, Cauliflower, Peanuts, Mustard Oil', 210, 6, 36, 4.5, 4, 3, 220, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2062', 'Cholar Dal with Coconut', 'Bengali', 'Breakfast/Lunch', 'Curry', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 30, 3, 'Chana Dal, Coconut Slices, Cumin, Clove, Cinnamon, Bay Leaf', 250, 12, 38, 5.0, 7, 3, 270, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2063', 'Baked Luchi Aloo Dom', 'Bengali', 'Breakfast', 'Bread', 'Vegetarian', 'Yes', 'Mild', 'Medium', 25, 20, 2, 'Whole Wheat Atta, Potatoes, Cumin, Tomato, Mustard Oil', 270, 7, 48, 5.0, 6, 3, 290, 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2064', 'Bengali Rohu Fish Macher Jhol', 'Bengali', 'Lunch/Dinner', 'Curry', 'Non-Vegetarian', 'No', 'Mild', 'Medium', 15, 20, 2, 'Rohu Fish, Potato, Papaya, Nigella Seeds, Turmeric, Mustard Oil', 260, 28, 12, 10.0, 3, 1, 360, 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2065', 'Grilled Begun Bhaja (Eggplant)', 'Bengali', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 15, 2, 'Eggplant Slices, Turmeric, Rice Flour, Mustard Oil', 140, 3, 18, 6.0, 5, 3, 220, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2066', 'Bengali Shukto (Mix Veg Stew)', 'Bengali', 'Lunch', 'Curry', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 25, 3, 'Bitter Gourd, Raw Banana, Papaya, Drumstick, Mustard Paste', 190, 5, 28, 5.0, 7, 4, 250, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2067', 'Lau Ghonto (Bottle Gourd Stew)', 'Bengali', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 20, 3, 'Bottle Gourd, Bori (Lentil Dumplings), Cumin, Mustard Oil', 150, 5, 22, 4.0, 6, 3, 230, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2068', 'Dhokar Dalna (Lentil Cake Curry)', 'Bengali', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Mild', 'Medium', 25, 30, 3, 'Chana Dal, Matar Dal, Potato, Ginger, Cumin, Tomato', 270, 14, 40, 5.5, 7, 3, 310, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2069', 'Potoler Dalna (Pointed Gourd)', 'Bengali', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 20, 2, 'Pointed Gourd (Parwal), Potato, Ginger, Cumin, Turmeric', 180, 4, 26, 6.0, 6, 4, 260, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2070', 'Mocha Ghonto (Banana Flower Curry)', 'Bengali', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Medium', 25, 30, 3, 'Banana Flower, Potato, Coconut, Cumin, Garam Masala', 200, 6, 32, 4.5, 9, 3, 240, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2071', 'Baked Fish Kabiraji Cutlet', 'Bengali', 'Snack', 'Snack', 'Non-Vegetarian', 'No', 'Medium', 'Medium', 20, 20, 2, 'Bhetki Fish, Egg White, Whole Wheat Crumbs, Black Pepper', 230, 27, 12, 7.0, 2, 1, 340, 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2072', 'Pan-Fried Beetroot Chop', 'Bengali', 'Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 15, 2, 'Beetroot, Potato, Peanuts, Bhaja Masala, Oats Crumbs', 170, 5, 28, 4.0, 6, 4, 230, 'No', 'No', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2073', 'Steamed Katla Fish Bhapa', 'Bengali', 'Dinner', 'Steamed', 'Non-Vegetarian', 'No', 'Medium', 'Easy', 15, 15, 2, 'Katla Fish Fillet, Mustard Paste, Green Chili, Turmeric', 250, 29, 4, 12.0, 1, 0, 350, 'No', 'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2074', 'Bengali Pumpkin Chhachchari', 'Bengali', 'Lunch/Dinner', 'Sabzi', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 15, 2, 'Pumpkin, Panch Phoron, Green Chili, Mustard Oil', 135, 3, 22, 3.5, 5, 5, 210, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2075', 'Chana Muri (Spiced Puffed Rice)', 'Bengali', 'Snack', 'Snack', 'Vegetarian', 'Yes', 'Medium', 'Easy', 5, 0, 2, 'Puffed Rice (Muri), Boiled Chana, Mustard Oil, Cucumber, Lemon', 160, 6, 30, 2.5, 4, 2, 220, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),

    # INDO-CHINESE & INTERNATIONAL (15 Dishes)
    ('D2076', 'Whole Wheat Veg Hack Noodles', 'Indo-Chinese', 'Breakfast/Snack', 'Indo-Chinese', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 12, 2, 'Whole Wheat Noodles, Capsicum, Cabbage, Carrot, Soy Sauce', 230, 7, 42, 3.5, 6, 3, 310, 'Yes', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2077', 'Indo-Chinese Veg Manchow Soup', 'Indo-Chinese', 'Dinner/Snack', 'Soup', 'Vegetarian', 'Yes', 'Spicy', 'Easy', 10, 15, 2, 'Cabbage, Carrot, Mushroom, Garlic, Ginger, Soy Sauce', 110, 4, 16, 2.0, 4, 2, 340, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2078', 'Steamed Veg Momo Dumplings', 'Indo-Chinese', 'Snack', 'Steamed', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 15, 3, 'Whole Wheat Wrapper, Cabbage, Onion, Carrot, Garlic Sauce', 170, 5, 32, 2.0, 4, 2, 280, 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2079', 'Dry Chilli Paneer (Low Oil)', 'Indo-Chinese', 'Lunch/Dinner', 'Stir-Fry', 'Vegetarian', 'No', 'Spicy', 'Medium', 15, 12, 2, 'Paneer, Bell Peppers, Capsicum, Green Chili, Soy Sauce', 260, 17, 12, 15.0, 3, 3, 350, 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2080', 'Dry Chilli Tofu Stir Fry', 'Indo-Chinese', 'Lunch/Dinner', 'Stir-Fry', 'Vegetarian', 'Yes', 'Spicy', 'Medium', 15, 12, 2, 'Firm Tofu, Bell Peppers, Capsicum, Green Chili, Soy Sauce', 220, 18, 10, 11.0, 4, 2, 330, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2081', 'Cauliflower Fried Rice (Low Carb)', 'Indo-Chinese', 'Lunch/Dinner', 'Rice', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 10, 2, 'Grated Cauliflower, Peas, Carrots, Spring Onion, Soy Sauce', 140, 6, 16, 5.0, 7, 4, 290, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2082', 'Stir-Fry Garlic Veggies in Dark Sauce', 'Indo-Chinese', 'Lunch/Dinner', 'Stir-Fry', 'Vegetarian', 'Yes', 'Medium', 'Easy', 10, 10, 2, 'Broccoli, Mushroom, Babycorn, Capsicum, Garlic', 130, 6, 18, 3.5, 6, 3, 300, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2083', 'Steamed Veg Ball Manchurian', 'Indo-Chinese', 'Lunch/Dinner', 'Curry', 'Vegetarian', 'Yes', 'Medium', 'Medium', 20, 15, 3, 'Cabbage, Carrot, Oats Flour, Ginger, Soy Sauce', 180, 6, 28, 4.0, 5, 3, 320, 'No', 'No', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2084', 'Whole Wheat Veggie Pizza', 'Continental', 'CheatMeal', 'Main', 'Vegetarian', 'No', 'Mild', 'Medium', 20, 15, 2, 'Whole Wheat Crust, Tomato Sauce, Low-Fat Mozzarella, Bell Peppers', 380, 16, 52, 11.0, 6, 4, 420, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2085', 'Baked Paneer Tikka Burger', 'Continental', 'CheatMeal', 'Main', 'Vegetarian', 'No', 'Medium', 'Medium', 20, 15, 2, 'Whole Wheat Bun, Grilled Paneer Patty, Lettuce, Tomato', 390, 20, 48, 12.0, 5, 4, 430, 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2086', 'Air-Fried Sweet Potato Wedges', 'Continental', 'CheatMeal/Snack', 'Snack', 'Vegetarian', 'Yes', 'Mild', 'Easy', 10, 20, 2, 'Sweet Potato, Olive Oil, Paprika, Oregano, Black Pepper', 190, 4, 38, 3.5, 6, 7, 210, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2087', 'Low-Calorie Dark Chocolate Oats Brownie', 'Continental', 'CheatMeal/Dessert', 'Dessert', 'Vegetarian', 'Yes', 'Mild', 'Easy', 15, 20, 4, 'Oats Flour, Cocoa Powder, Seedless Dates, Almond Milk', 160, 5, 26, 4.0, 5, 7, 70, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2088', 'Baked Falafel Hummus Wrap', 'Mediterranean', 'CheatMeal/Lunch', 'Main', 'Vegetarian', 'Yes', 'Mild', 'Medium', 20, 20, 2, 'Baked Chickpea Falafel, Whole Wheat Wrap, Hummus, Cucumber', 360, 15, 54, 8.0, 9, 3, 380, 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2089', 'Whey Oats Protein Smoothie', 'Continental', 'PostWorkout', 'Beverage', 'Vegetarian', 'No', 'Mild', 'Easy', 5, 0, 1, 'Rolled Oats, Banana, Plant Protein, Almond Milk', 290, 26, 38, 4.0, 6, 8, 120, 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes'),
    ('D2090', 'High Protein Egg White Spinach Omelette', 'Continental', 'PostWorkout', 'Scramble', 'Egg-itarian', 'No', 'Mild', 'Easy', 5, 10, 1, 'Egg Whites, Fresh Spinach, Mushroom, Black Pepper, Olive Oil', 180, 24, 6, 6.0, 2, 1, 290, 'No', 'No', 'No', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes')
]

for p in file_paths:
    try:
        wb = openpyxl.load_workbook(p)
        sheet = wb['Dishes_Database']
        existing_ids = set()
        for r in range(2, sheet.max_row + 1):
            val = sheet.cell(r, 1).value
            if val: existing_ids.add(str(val).strip())
        
        added = 0
        for row in more_dishes:
            if row[0] not in existing_ids:
                sheet.append(list(row))
                added += 1
        
        wb.save(p)
        print(f'Saved {added} new dishes to {p}. Total rows: {sheet.max_row}')
    except Exception as e:
        print(f'Error updating {p}: {e}')
