import re

extra_recipes = '''
  // --- ADDITIONAL BREAKFAST DISHES ---
  {
    id: "brk-1",
    name: "Quinoa Veggie Upma",
    cuisine: "North Indian",
    mealType: "Breakfast",
    prepTime: 15,
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 240, protein: 9, carbs: 36, fat: 5, fiber: 7 },
    micros: { iron: 3.8, calcium: 70, vitC: 20, sodium: 260 },
    cost: 50,
    ingredients: ["Quinoa", "Carrots", "Peas", "Mustard seeds", "Curry leaves", "Lemon juice"],
    instructions: ["Rinse quinoa and boil.", "Temper mustard seeds and saute carrots and peas.", "Mix quinoa and lemon juice."],
    healthBenefits: ["Complete protein with all 9 essential amino acids", "Low GI for blood sugar management"],
    suitableFor: ["Diabetes", "Weight Loss", "PCOS", "Gluten Intolerance"],
    medicalAdvice: "Quinoa is a low-glycemic index pseudo-cereal that prevents postprandial glucose spikes in diabetic patients."
  },
  {
    id: "brk-2",
    name: "Palak Oats Besan Cheela",
    cuisine: "North Indian",
    mealType: "Breakfast",
    prepTime: 15,
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 220, protein: 11, carbs: 32, fat: 4.5, fiber: 6 },
    micros: { iron: 4.5, calcium: 110, vitC: 18, sodium: 280 },
    cost: 35,
    ingredients: ["Besan (gram flour)", "Rolled oats flour", "Fresh spinach puree", "Ajwain", "Green chilies"],
    instructions: ["Mix besan, oats flour, and spinach puree with water into batter.", "Pour onto hot skillet and cook both sides with 1/2 tsp oil."],
    healthBenefits: ["High folic acid and iron from spinach", "High fiber and plant protein"],
    suitableFor: ["Anemia", "Diabetes", "Hypertension", "PCOS"],
    medicalAdvice: "Folic acid and non-heme iron in spinach assist red blood cell production."
  },
  {
    id: "brk-3",
    name: "Moong Dal Steamed Idli",
    cuisine: "South Indian",
    mealType: "Breakfast",
    prepTime: 20,
    difficulty: "Medium",
    servings: 3,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegetarian",
    macros: { calories: 180, protein: 12, carbs: 28, fat: 2.5, fiber: 5 },
    micros: { iron: 3.5, calcium: 80, vitC: 10, sodium: 240 },
    cost: 40,
    ingredients: ["Yellow moong dal", "Low-fat curd", "Enos fruit salt", "Mustard seeds", "Curry leaves"],
    instructions: ["Soak moong dal and grind to batter with curd.", "Steam in idli molds for 12 mins.", "Temper with mustard seeds."],
    healthBenefits: ["High protein zero-oil steamed breakfast", "Low calorie high satiety"],
    suitableFor: ["Weight Loss", "Diabetes", "Senior Citizens", "Fatty Liver"],
    medicalAdvice: "Steamed yellow moong dal idlis provide high protein density with minimal digestive load."
  },
  {
    id: "brk-4",
    name: "Foxtail Millet Ven Pongal",
    cuisine: "South Indian",
    mealType: "Breakfast",
    prepTime: 20,
    difficulty: "Easy",
    servings: 3,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegetarian",
    macros: { calories: 250, protein: 10, carbs: 42, fat: 5, fiber: 6 },
    micros: { iron: 4.1, calcium: 90, vitC: 5, sodium: 260 },
    cost: 45,
    ingredients: ["Foxtail millet", "Yellow moong dal", "Black pepper", "Cumin", "Ginger", "Ghee"],
    instructions: [
      "Pressure cook foxtail millet and moong dal until soft.",
      "Temper cracked black pepper, cumin seeds, and crushed ginger in 1 tsp ghee.",
      "Mix into cooked millet and serve warm."
    ],
    healthBenefits: ["High dietary fiber millet", "Low glycemic index", "Easy on stomach"],
    suitableFor: ["Diabetes", "Gluten Intolerance", "Senior Citizens"],
    medicalAdvice: "Foxtail millet has a lower glycemic response than white rice, stabilizing blood sugar levels."
  },
  {
    id: "brk-5",
    name: "Sprouted Chana Chaat Bowl",
    cuisine: "North Indian",
    mealType: "Breakfast",
    prepTime: 15,
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 195, protein: 13, carbs: 31, fat: 2.8, fiber: 8 },
    micros: { iron: 4.8, calcium: 85, vitC: 22, sodium: 290 },
    cost: 30,
    ingredients: ["Sprouted black chana", "Tomato", "Onion", "Lemon juice", "Chaat masala", "Cucumber"],
    instructions: ["Steam sprouted black chana lightly.", "Toss with diced tomatoes, onions, cucumber, and lemon juice."],
    healthBenefits: ["High plant iron and fiber", "Vitamin C boosts iron bio-availability"],
    suitableFor: ["Anemia", "Diabetes", "Weight Loss"],
    medicalAdvice: "Sprouted black chana offers bio-available plant iron paired with natural Vitamin C from lemon juice."
  },
  {
    id: "brk-6",
    name: "Chia Seed Berry Pudding",
    cuisine: "Continental",
    mealType: "Breakfast",
    prepTime: 10,
    difficulty: "Easy",
    servings: 1,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 175, protein: 6, carbs: 22, fat: 7.5, fiber: 10 },
    micros: { iron: 2.5, calcium: 260, vitC: 15, sodium: 90 },
    cost: 60,
    ingredients: ["Chia seeds", "Unsweetened almond milk", "Strawberries", "Blueberries", "Vanilla extract"],
    instructions: ["Soak chia seeds in almond milk overnight.", "Top with fresh berries before serving."],
    healthBenefits: ["High omega-3 fatty acids", "Rich in soluble fiber and antioxidants"],
    suitableFor: ["High Cholesterol", "Heart Health", "Diabetes", "Lactose Intolerance"],
    medicalAdvice: "Chia seeds contain ALA omega-3 fatty acids which support cardiovascular health."
  },
  {
    id: "brk-7",
    name: "Steamed Methi Muthia",
    cuisine: "Gujarati",
    mealType: "Breakfast",
    prepTime: 20,
    difficulty: "Medium",
    servings: 3,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 190, protein: 8, carbs: 30, fat: 3.5, fiber: 5 },
    micros: { iron: 3.2, calcium: 110, vitC: 14, sodium: 240 },
    cost: 35,
    ingredients: ["Besan", "Methi leaves", "Whole wheat flour", "Sesame seeds", "Turmeric"],
    instructions: ["Knead ingredients into dough rolls.", "Steam for 20 mins, slice and serve with mustard tempering."],
    healthBenefits: ["Fenugreek regulates blood sugar", "Steamed low fat breakfast"],
    suitableFor: ["Diabetes", "Weight Loss", "Senior Citizens"],
    medicalAdvice: "Fenugreek seeds and leaves assist glucose tolerance and insulin regulation."
  },
  {
    id: "brk-8",
    name: "Pesarattu (Sprouted Moong Dosa)",
    cuisine: "South Indian",
    mealType: "Breakfast",
    prepTime: 15,
    difficulty: "Medium",
    servings: 2,
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 210, protein: 13, carbs: 33, fat: 3.0, fiber: 7 },
    micros: { iron: 4.1, calcium: 90, vitC: 12, sodium: 240 },
    cost: 40,
    ingredients: ["Sprouted green moong", "Ginger", "Green chili", "Cumin seeds", "Onions"],
    instructions: ["Grind soaked moong with ginger and green chili.", "Spread batter on hot skillet like a dosa."],
    healthBenefits: ["High protein low carb crepe", "Rich in folate and potassium"],
    suitableFor: ["PCOS", "Diabetes", "Muscle Building"],
    medicalAdvice: "Sprouted green moong provides 13g protein per serving with complex low-GI carbs."
  },
  {
    id: "brk-9",
    name: "Stuffed Gobi Whole Wheat Paratha",
    cuisine: "Punjabi",
    mealType: "Breakfast",
    prepTime: 20,
    difficulty: "Medium",
    servings: 2,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 260, protein: 8, carbs: 46, fat: 4.5, fiber: 6 },
    micros: { iron: 3.1, calcium: 75, vitC: 28, sodium: 300 },
    cost: 35,
    ingredients: ["Whole wheat atta", "Grated cauliflower", "Ajwain", "Green chili", "Coriander"],
    instructions: ["Stuff grated spiced cauliflower into whole wheat dough.", "Roast on skillet with minimal oil."],
    healthBenefits: ["High fiber whole grain", "Sulforaphane antioxidant from cauliflower"],
    suitableFor: ["Diabetes", "Healthy Lifestyle"],
    medicalAdvice: "Cauliflower provides fiber and sulforaphane while whole wheat flour provides sustained energy release."
  },
  {
    id: "brk-10",
    name: "Sprouted Kanda Poha",
    cuisine: "Maharashtrian",
    mealType: "Breakfast",
    prepTime: 12,
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 220, protein: 8, carbs: 36, fat: 4.5, fiber: 5 },
    micros: { iron: 4.2, calcium: 65, vitC: 24, sodium: 240 },
    cost: 30,
    ingredients: ["Flattened rice (poha)", "Sprouted moong", "Onion", "Mustard seeds", "Turmeric", "Lemon juice"],
    instructions: ["Saute onions, mustard seeds, and sprouted moong.", "Add rinsed poha, turmeric, and lemon juice."],
    healthBenefits: ["Boosted protein from sprouted moong", "Iron enriched poha"],
    suitableFor: ["Anemia", "Weight Loss", "Diabetes"],
    medicalAdvice: "Adding sprouted moong elevates the protein and fiber content of traditional poha."
  },

  // --- ADDITIONAL POST-WORKOUT DISHES ---
  {
    id: "post-1",
    name: "Tofu Spinach Protein Scramble",
    cuisine: "Continental",
    mealType: "PostWorkout",
    prepTime: 10,
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 220, protein: 20, carbs: 10, fat: 11.0, fiber: 4 },
    micros: { iron: 5.5, calcium: 320, vitC: 22, sodium: 310 },
    cost: 65,
    ingredients: ["Firm tofu", "Fresh spinach", "Turmeric", "Black pepper", "Garlic", "Olive oil"],
    instructions: ["Crumble firm tofu.", "Saute minced garlic and spinach in 1 tsp olive oil.", "Add tofu, turmeric, black pepper, and cook 5 mins."],
    healthBenefits: ["High complete soy protein (20g)", "Calcium and magnesium for muscle recovery"],
    suitableFor: ["PostWorkout", "Muscle Building", "PCOS", "Lactose Intolerance"],
    medicalAdvice: "Provides 20g high-quality soy protein to support muscle protein synthesis post exercise."
  },
  {
    id: "post-2",
    name: "Whey Oats Protein Smoothie Bowl",
    cuisine: "Continental",
    mealType: "PostWorkout",
    prepTime: 5,
    difficulty: "Easy",
    servings: 1,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegetarian",
    macros: { calories: 290, protein: 26, carbs: 38, fat: 4.0, fiber: 6 },
    micros: { iron: 3.2, calcium: 280, vitC: 10, sodium: 120 },
    cost: 80,
    ingredients: ["Rolled oats", "Banana", "Plant protein powder", "Almond milk", "Chia seeds"],
    instructions: ["Blend oats, banana, protein powder, and almond milk until thick.", "Top with chia seeds."],
    healthBenefits: ["Rapid muscle glycogen recovery", "26g fast absorbing protein"],
    suitableFor: ["PostWorkout", "Muscle Building", "Increase Protein Intake"],
    medicalAdvice: "Optimal 3:1 carb-to-protein ratio for post-exercise glycogen replenishment and muscle repair."
  },
  {
    id: "post-3",
    name: "Grilled Chicken Breast Tikka",
    cuisine: "Punjabi",
    mealType: "PostWorkout",
    prepTime: 20,
    difficulty: "Medium",
    servings: 2,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Non-Vegetarian",
    macros: { calories: 280, protein: 32, carbs: 6, fat: 12.0, fiber: 2 },
    micros: { iron: 2.8, calcium: 110, vitC: 14, sodium: 360 },
    cost: 110,
    ingredients: ["Chicken breast fillets", "Low-fat curd marinade", "Garlic ginger paste", "Tikka spices", "Lemon juice"],
    instructions: ["Marinate chicken breast in curd and tikka spices for 15 mins.", "Grill on pan or skewer until cooked."],
    healthBenefits: ["32g pure lean protein", "Zero sugar low carbohydrate"],
    suitableFor: ["PostWorkout", "Muscle Building", "Diabetes", "Weight Loss"],
    medicalAdvice: "Provides 32g bio-available chicken protein with minimal subcutaneous fat impact."
  },

  // --- ADDITIONAL PRE-WORKOUT DISHES ---
  {
    id: "pre-1",
    name: "Banana Oats Cinnamon Bowl",
    cuisine: "Continental",
    mealType: "PreWorkout",
    prepTime: 10,
    difficulty: "Easy",
    servings: 1,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 240, protein: 7, carbs: 48, fat: 3.5, fiber: 6 },
    micros: { iron: 2.2, calcium: 60, vitC: 12, sodium: 80 },
    cost: 30,
    ingredients: ["Rolled oats", "Ripe banana", "Cinnamon powder", "Water / Almond milk"],
    instructions: ["Cook oats in water.", "Slice ripe banana on top and sprinkle cinnamon powder."],
    healthBenefits: ["Sustained energy carbs from oats", "Quick energy from banana potassium"],
    suitableFor: ["PreWorkout", "Healthy Lifestyle"],
    medicalAdvice: "Complex carbs combined with simple fruit sugars provide immediate and sustained energy during workouts."
  },
  {
    id: "pre-2",
    name: "Roasted Sweet Potato Chaat",
    cuisine: "North Indian",
    mealType: "PreWorkout",
    prepTime: 15,
    difficulty: "Easy",
    servings: 2,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegan",
    macros: { calories: 190, protein: 4, carbs: 42, fat: 1.5, fiber: 6 },
    micros: { iron: 1.8, calcium: 45, vitC: 25, sodium: 180 },
    cost: 30,
    ingredients: ["Sweet potato (Shakarkandi)", "Lemon juice", "Chaat masala", "Black salt", "Cumin powder"],
    instructions: ["Boil or roast sweet potatoes.", "Cube and toss with lemon juice, chaat masala, and cumin."],
    healthBenefits: ["Complex low-GI carbohydrates", "Rich in Beta-carotene and Potassium"],
    suitableFor: ["PreWorkout", "Diabetes", "Weight Loss"],
    medicalAdvice: "Sweet potatoes release glucose slowly into the bloodstream, preventing energy crashes."
  },

  // --- ADDITIONAL CHEAT MEAL / TREAT DISHES ---
  {
    id: "cheat-1",
    name: "Whole Wheat Veggie Paneer Pizza",
    cuisine: "Continental",
    mealType: "CheatMeal",
    prepTime: 20,
    difficulty: "Medium",
    servings: 2,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegetarian",
    macros: { calories: 380, protein: 17, carbs: 52, fat: 12.0, fiber: 6 },
    micros: { iron: 3.5, calcium: 340, vitC: 20, sodium: 420 },
    cost: 110,
    ingredients: ["Whole wheat dough crust", "Tomato sauce", "Low-fat paneer", "Capsicum & onions", "Mozzarella cheese"],
    instructions: ["Roll whole wheat base.", "Spread tomato sauce, paneer, veggies, and mozzarella.", "Bake at 200C for 15 mins."],
    healthBenefits: ["Whole wheat fiber base", "High protein paneer topping"],
    suitableFor: ["CheatMeal", "Healthy Lifestyle"],
    medicalAdvice: "A guilt-free cheat meal replacing refined maida with 100% whole wheat flour and protein-rich paneer."
  },
  {
    id: "cheat-2",
    name: "Baked Paneer Tikka Burger",
    cuisine: "Continental",
    mealType: "CheatMeal",
    prepTime: 20,
    difficulty: "Medium",
    servings: 2,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80",
    dietaryType: "Vegetarian",
    macros: { calories: 390, protein: 20, carbs: 48, fat: 12.0, fiber: 5 },
    micros: { iron: 3.8, calcium: 360, vitC: 15, sodium: 430 },
    cost: 100,
    ingredients: ["Whole wheat burger bun", "Grilled paneer patty", "Lettuce", "Tomato slices", "Mint chutney"],
    instructions: ["Grill paneer patty.", "Assemble whole wheat bun with lettuce, tomato, paneer, and mint chutney."],
    healthBenefits: ["High protein paneer burger", "Whole wheat bun fiber"],
    suitableFor: ["CheatMeal", "Muscle Building"],
    medicalAdvice: "Offers 20g protein in a comfort food format without shallow frying oils."
  }
'''

with open(r'd:\oil adulteration new\frontend\src\data\nutritionData.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Append before the last closing bracket of INDIAN_RECIPES_DATABASE
modified = content.replace('export const INDIAN_RECIPES_DATABASE = [', 'export const INDIAN_RECIPES_DATABASE = [' + extra_recipes)

with open(r'd:\oil adulteration new\frontend\src\data\nutritionData.js', 'w', encoding='utf-8') as f:
    f.write(modified)

print("Successfully expanded INDIAN_RECIPES_DATABASE in nutritionData.js!")
