import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ChevronLeft, Trash2, Share2, CheckCircle, AlertTriangle, Droplets, Thermometer, Zap, Activity } from 'lucide-react';
import { supabase } from '../lib/supabase';

export default function ScanDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [scan, setScan] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  useEffect(() => {
    supabase.from('analysis_results').select('*').eq('id', id).single()
      .then(({ data, error }) => {
        if (data) setScan(data);
        setLoading(false);
      });
  }, [id]);

  const handleDelete = async () => {
    await supabase.from('analysis_results').delete().eq('id', id);
    navigate(-1);
  };

  const handleShare = () => {
    if (!scan) return;
    const text = [
      `PureOil Scan Report`,
      `─────────────────`,
      `Oil Type: ${scan.oil_type || 'Unknown'}`,
      `Quality: ${scan.quality}`,
      `Purity: ${scan.purity}%`,
      `Date: ${new Date(scan.timestamp).toLocaleString()}`,
      scan.vendor ? `Vendor: ${scan.vendor}` : null,
      scan.notes ? `Notes: ${scan.notes}` : null,
      `─────────────────`,
      `Generated by PureOil App`
    ].filter(Boolean).join('\n');

    if (navigator.share) {
      navigator.share({ title: 'PureOil Scan Report', text }).catch(() => {});
    } else {
      navigator.clipboard?.writeText(text).then(() => alert('Report copied to clipboard!'));
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen theme-bg flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-[var(--border-color)] border-t-[#d4af37] rounded-full animate-spin" />
      </div>
    );
  }

  if (!scan) {
    return (
      <div className="min-h-screen theme-bg flex flex-col items-center justify-center gap-4 p-6">
        <Droplets size={48} className="text-[var(--text-muted)]" />
        <p className="theme-text font-bold text-lg">Scan not found</p>
        <button onClick={() => navigate(-1)} className="btn-primary px-6 py-3 text-sm">Go Back</button>
      </div>
    );
  }

  const isSafe = scan.quality !== 'Unsafe';
  const qualityColor = isSafe ? 'text-green-500' : 'text-red-500';
  const qualityBg = isSafe ? 'bg-green-500/10 border-green-500/20' : 'bg-red-500/10 border-red-500/20';
  const StatusIcon = isSafe ? CheckCircle : AlertTriangle;

  const Field = ({ label, value }) => {
    if (value === null || value === undefined || value === '') return null;
    return (
      <div className="flex justify-between items-start py-3 border-b border-[var(--border-color)] last:border-0">
        <span className="text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)] mt-0.5">{label}</span>
        <span className="theme-text font-semibold text-sm text-right max-w-[60%]">{value}</span>
      </div>
    );
  };

  const SensorField = ({ icon: Icon, label, value, unit }) => {
    if (value === null || value === undefined) return null;
    return (
      <div className="card p-4 flex flex-col gap-1 items-center text-center">
        <Icon size={18} className="text-[#d4af37] mb-1" />
        <p className="text-[9px] font-bold uppercase tracking-widest text-[var(--text-muted)]">{label}</p>
        <p className="theme-text font-black text-lg font-mono">{typeof value === 'number' ? value.toFixed(2) : value}<span className="text-[10px] text-[var(--text-muted)] font-normal ml-0.5">{unit}</span></p>
      </div>
    );
  };

  return (
    <div className="min-h-screen theme-bg animate-fade-in pb-10">
      {/* Header */}
      <div className="flex items-center justify-between px-4 pt-6 pb-4 border-b border-[var(--border-color)]">
        <button onClick={() => navigate(-1)} className="p-2 rounded-full bg-[var(--bg-elevated)] theme-text">
          <ChevronLeft size={22} />
        </button>
        <h1 className="theme-text font-black text-base tracking-wide">Scan Detail</h1>
        <div className="flex items-center gap-2">
          <button onClick={handleShare} className="p-2 rounded-full bg-[var(--bg-elevated)] text-[#d4af37]">
            <Share2 size={18} />
          </button>
          <button onClick={() => setShowDeleteConfirm(true)} className="p-2 rounded-full bg-red-500/10 text-red-500">
            <Trash2 size={18} />
          </button>
        </div>
      </div>

      <div className="px-5 pt-5 flex flex-col gap-5">
        {/* Quality Hero */}
        <div className={`card border ${qualityBg} flex flex-col items-center justify-center py-8 gap-3`}>
          <div className={`w-16 h-16 rounded-full ${qualityBg} border flex items-center justify-center`}>
            <StatusIcon size={32} className={qualityColor} />
          </div>
          <div className="text-center">
            <p className={`text-3xl font-black ${qualityColor}`}>{scan.quality}</p>
            <p className="text-[var(--text-muted)] text-sm mt-1">{scan.oil_type || 'Unknown Oil Type'}</p>
          </div>
          {scan.purity !== null && scan.purity !== undefined && (
            <div className="flex items-baseline gap-1">
              <span className="text-4xl font-black theme-text font-mono">{scan.purity?.toFixed(1)}</span>
              <span className="text-[var(--text-muted)] font-bold">% purity</span>
            </div>
          )}
        </div>

        {/* Core Details */}
        <div className="card p-0 overflow-hidden shadow-sm">
          <div className="px-4 py-3 border-b border-[var(--border-color)] bg-[var(--bg-elevated)]">
            <h2 className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)]">Scan Details</h2>
          </div>
          <div className="px-4">
            <Field label="Date & Time" value={new Date(scan.timestamp).toLocaleString([], { dateStyle: 'full', timeStyle: 'short' })} />
            <Field label="Oil Type" value={scan.oil_type} />
            <Field label="Quality" value={scan.quality} />
            <Field label="Vendor / Location" value={scan.vendor} />
            <Field label="Sample ID" value={scan.id} />
            <Field label="Notes" value={scan.notes} />
            {scan.likely_adulterants?.length > 0 && (
              <Field label="Detected Adulterants" value={scan.likely_adulterants.join(', ')} />
            )}
          </div>
        </div>

        {/* Sensor Snapshot */}
        {scan.sensor_snapshot && Object.keys(scan.sensor_snapshot).length > 0 && (
          <div>
            <h2 className="text-[10px] font-black uppercase tracking-widest text-[var(--text-muted)] mb-3 pl-1">Sensor Readings</h2>
            <div className="grid grid-cols-2 gap-3">
              <SensorField icon={Droplets} label="Density" value={scan.sensor_snapshot?.density_gcm3} unit="g/cm³" />
              <SensorField icon={Activity} label="TDS" value={scan.sensor_snapshot?.tds_ppm} unit="ppm" />
              <SensorField icon={Thermometer} label="Temperature" value={scan.sensor_snapshot?.temperature_c} unit="°C" />
              <SensorField icon={Zap} label="Turbidity" value={scan.sensor_snapshot?.turbidity_ntu} unit="NTU" />
            </div>
          </div>
        )}

        {/* Adulterant Warning */}
        {!isSafe && (
          <div className="card border border-red-500/20 bg-red-500/5 p-4 flex gap-3">
            <AlertTriangle size={20} className="text-red-500 shrink-0 mt-0.5" />
            <div>
              <p className="text-red-500 font-black text-xs uppercase tracking-widest mb-1">Contamination Detected</p>
              <p className="text-[var(--text-secondary)] text-sm leading-relaxed">
                This sample was flagged as unsafe. Consider filing an FSSAI violation report and stopping the sale of this product immediately.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Delete Confirm Dialog */}
      {showDeleteConfirm && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-6 bg-black/60 backdrop-blur-sm animate-fade-in" onClick={() => setShowDeleteConfirm(false)}>
          <div className="bg-[var(--bg-card)] border border-[var(--border-color)] rounded-3xl p-6 w-full max-w-xs text-center shadow-2xl animate-slide-up" onClick={e => e.stopPropagation()}>
            <div className="w-14 h-14 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-4 border border-red-500/20">
              <Trash2 size={24} className="text-red-500" />
            </div>
            <h3 className="theme-text font-black text-lg mb-2">Delete this scan?</h3>
            <p className="text-[var(--text-secondary)] text-sm mb-6">This scan record will be permanently deleted from the database.</p>
            <div className="flex gap-3">
              <button onClick={() => setShowDeleteConfirm(false)} className="flex-1 py-3 rounded-xl font-bold bg-[var(--bg-elevated)] theme-text border border-[var(--border-color)]">Cancel</button>
              <button onClick={handleDelete} className="flex-1 py-3 bg-red-500 text-white rounded-xl font-bold shadow-[0_4px_15px_rgba(239,68,68,0.3)]">Delete</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
