// Oil Reference Database — pure baseline sensor ranges for adulteration detection
// All ranges based on known food-science data for edible oils

export const OIL_REFERENCE_DATA = [
  {
    oilName: 'Mustard Oil',
    color: '#D4A017',
    descriptor: 'Pungent, golden-yellow. FSSAI staple oil.',
    temperatureRange: { min: 22, max: 35 },
    pressureRange: { min: 1005, max: 1020 },
    densityRange: { min: 0.910, max: 0.925 },
    lightAbsorptionRange: { min: 180, max: 320 },
    commonAdulterants: ['Argemone oil', 'Mineral oil', 'Kesari dal oil'],
  },
  {
    oilName: 'Olive Oil',
    color: '#A8C060',
    descriptor: 'Pale greenish-gold. Rich in monounsaturates.',
    temperatureRange: { min: 20, max: 30 },
    pressureRange: { min: 1008, max: 1018 },
    densityRange: { min: 0.910, max: 0.916 },
    lightAbsorptionRange: { min: 290, max: 480 },
    commonAdulterants: ['Sunflower oil', 'Soybean oil', 'Pomace oil'],
  },
  {
    oilName: 'Coconut Oil',
    color: '#F5F0E8',
    descriptor: 'White/pale yellow. Solid below 24°C.',
    temperatureRange: { min: 25, max: 38 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.908, max: 0.921 },
    lightAbsorptionRange: { min: 80, max: 160 },
    commonAdulterants: ['Palm kernel oil', 'Vanaspati'],
  },
  {
    oilName: 'Sunflower Oil',
    color: '#F5D76A',
    descriptor: 'Light golden. Neutral flavour, high smoke point.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.918, max: 0.923 },
    lightAbsorptionRange: { min: 150, max: 280 },
    commonAdulterants: ['Mineral oil', 'Rice bran oil'],
  },
  {
    oilName: 'Groundnut Oil',
    color: '#C8852A',
    descriptor: 'Amber gold. Nutty flavour, high smoke point.',
    temperatureRange: { min: 22, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.912, max: 0.920 },
    lightAbsorptionRange: { min: 200, max: 350 },
    commonAdulterants: ['Palm oil', 'Mineral oil'],
  },
  {
    oilName: 'Palm Oil',
    color: '#D95A1A',
    descriptor: 'Deep orange-red. Semi-solid at room temp.',
    temperatureRange: { min: 28, max: 40 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.891, max: 0.899 },
    lightAbsorptionRange: { min: 340, max: 560 },
    commonAdulterants: ['Palm kernel oil', 'Vanaspati', 'Mineral oil'],
  },
  {
    oilName: 'Sesame Oil',
    color: '#A0622A',
    descriptor: 'Medium amber-brown. Strong nutty aroma.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.915, max: 0.924 },
    lightAbsorptionRange: { min: 260, max: 420 },
    commonAdulterants: ['Rice bran oil', 'Groundnut oil', 'Mineral oil'],
  },
  {
    oilName: 'Rice Bran Oil',
    color: '#D4B060',
    descriptor: 'Light golden. High oryzanol content.',
    temperatureRange: { min: 22, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.916, max: 0.921 },
    lightAbsorptionRange: { min: 170, max: 300 },
    commonAdulterants: ['Palmolein', 'Mineral oil'],
  },
  {
    oilName: 'Soybean Oil',
    color: '#E8D87A',
    descriptor: 'Pale yellow. Mild flavour, high polyunsaturates.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.919, max: 0.925 },
    lightAbsorptionRange: { min: 140, max: 260 },
    commonAdulterants: ['Palm oil', 'Mineral oil', 'Corn oil'],
  },
  {
    oilName: 'Canola Oil',
    color: '#EDE890',
    descriptor: 'Light yellow. Very low saturated fat.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.914, max: 0.920 },
    lightAbsorptionRange: { min: 130, max: 250 },
    commonAdulterants: ['Soybean oil', 'Palm oil'],
  },
  {
    oilName: 'Corn Oil',
    color: '#E8C84A',
    descriptor: 'Golden yellow. Rich in linoleic acid.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.917, max: 0.925 },
    lightAbsorptionRange: { min: 160, max: 290 },
    commonAdulterants: ['Soybean oil', 'Mineral oil'],
  },
  {
    oilName: 'Cottonseed Oil',
    color: '#D8C890',
    descriptor: 'Pale gold. Used in snack frying.',
    temperatureRange: { min: 22, max: 36 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.918, max: 0.926 },
    lightAbsorptionRange: { min: 180, max: 310 },
    commonAdulterants: ['Palm oil', 'Mineral oil'],
  },
  {
    oilName: 'Safflower Oil',
    color: '#E8A830',
    descriptor: 'Golden orange. Highest linoleic acid content.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.922, max: 0.927 },
    lightAbsorptionRange: { min: 190, max: 330 },
    commonAdulterants: ['Sunflower oil', 'Soybean oil'],
  },
  {
    oilName: 'Flaxseed Oil',
    color: '#8B5A1A',
    descriptor: 'Dark amber. Highest omega-3, oxidises quickly.',
    temperatureRange: { min: 15, max: 28 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.926, max: 0.931 },
    lightAbsorptionRange: { min: 350, max: 520 },
    commonAdulterants: ['Soybean oil', 'Mineral oil'],
  },
  {
    oilName: 'Almond Oil',
    color: '#E8D0A0',
    descriptor: 'Pale golden. Nutty, used in baking & skin.',
    temperatureRange: { min: 18, max: 32 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.910, max: 0.915 },
    lightAbsorptionRange: { min: 120, max: 220 },
    commonAdulterants: ['Apricot kernel oil', 'Mineral oil'],
  },
  {
    oilName: 'Castor Oil',
    color: '#F0EDD8',
    descriptor: 'Very pale yellow. High viscosity, industrial/medicinal.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.952, max: 0.965 },
    lightAbsorptionRange: { min: 90, max: 170 },
    commonAdulterants: ['Mineral oil', 'Linseed oil'],
  },
  {
    oilName: 'Avocado Oil',
    color: '#3A7A30',
    descriptor: 'Dark green. Highest smoke point of all oils.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.910, max: 0.914 },
    lightAbsorptionRange: { min: 310, max: 500 },
    commonAdulterants: ['Soybean oil', 'Sunflower oil'],
  },
  {
    oilName: 'Walnut Oil',
    color: '#C09040',
    descriptor: 'Light amber. High omega-3, delicate flavour.',
    temperatureRange: { min: 18, max: 30 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.920, max: 0.926 },
    lightAbsorptionRange: { min: 240, max: 390 },
    commonAdulterants: ['Hazelnut oil', 'Mineral oil'],
  },
  {
    oilName: 'Grapeseed Oil',
    color: '#C8D890',
    descriptor: 'Pale greenish-yellow. Light flavour, high smoke.',
    temperatureRange: { min: 20, max: 35 },
    pressureRange: { min: 1005, max: 1018 },
    densityRange: { min: 0.919, max: 0.926 },
    lightAbsorptionRange: { min: 155, max: 270 },
    commonAdulterants: ['Soybean oil', 'Sunflower oil'],
  },
  {
    oilName: 'Vegetable Oil Blend',
    color: '#E8E098',
    descriptor: 'Light yellow blend. Generic multi-use cooking oil.',
    temperatureRange: { min: 20, max: 38 },
    pressureRange: { min: 1005, max: 1020 },
    densityRange: { min: 0.915, max: 0.924 },
    lightAbsorptionRange: { min: 150, max: 290 },
    commonAdulterants: ['Mineral oil', 'Vanaspati', 'Palm olein'],
  },
];

export const getOilByName = (name) =>
  OIL_REFERENCE_DATA.find((o) => o.oilName === name) || null;
